# Generated by Django 3.0.6 on 2020-05-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=100)),
                ('war_name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
