# Generated by Django 3.0.6 on 2020-06-05 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dict_word'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dict',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['id']},
        ),
    ]
